version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: vishnu
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: fitness
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: fitness_redis
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fitness_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local