version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: vishnu
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: fitness
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local